GET http://localhost:3000/api/auth/authorize/access-page?path=/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MGRiZGIyNS02OTJiLTQ0ZTItODA0MC04ZjFlNmNjMjkyYWEiLCJpYXQiOjE3NDA0NDc2MjR9.C20AjSB9tkTAGzrszJ3_4iywWQ7S22_-_2S0kAAoXNE