GET http://localhost:3000/api/auth/authorize/access-page
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5OGFlMjA5Ni1mN2Q1LTQ5NjAtOTU1NS1iOGQ1OTUzMDQzZDkiLCJpYXQiOjE3NDA0MTE1MjZ9.LooTMMLH664WTG4mDt26YUBN-ZfNi2R9sivyfe8E7Ys